authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
name    = "MoarDicts"
uuid    = "15001077-af68-4cc7-9614-a197249ba55d"
version = "0.1.0"

[compat]
julia = "1"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test   = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
