authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
name    = "FlatCollections"
uuid    = "15001077-af68-4cc7-9614-a197249ba55d"
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
